import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { db } from '../lib/db';
import { vehicles, vehicleImages, vehicleFeatures, dealershipSettings, users } from '../lib/db/schema';
import { generateSlug } from '../lib/utils';
import * as bcrypt from 'bcryptjs';

async function seed() {
  console.log('🌱 Seeding database...');

  console.log('Creating dealership settings...');
  await db.insert(dealershipSettings).values({
    businessName: 'TD Car Centre',
    phone: '+44 1234 567890',
    email: 'sales@tdcarcentre.co.uk',
    address: '123 Premium Drive, London, SW1A 1AA',
    companyNumber: '12345678',
    openingHours: JSON.stringify({
      monday: '9:00 AM - 6:00 PM',
      tuesday: '9:00 AM - 6:00 PM',
      wednesday: '9:00 AM - 6:00 PM',
      thursday: '9:00 AM - 6:00 PM',
      friday: '9:00 AM - 6:00 PM',
      saturday: '10:00 AM - 5:00 PM',
      sunday: 'Closed',
    }),
    instagramUrl: 'https://instagram.com/tdcarcentre',
    facebookUrl: 'https://facebook.com/tdcarcentre',
  });

  console.log('Creating admin user...');
  const passwordHash = await bcrypt.hash('admin123', 10);
  await db.insert(users).values({
    name: 'Admin User',
    email: 'admin@tdcarcentre.co.uk',
    passwordHash,
    role: 'admin',
  });

  console.log('Creating luxury vehicles...');

  const luxuryVehicles = [
    {
      title: '2023 Porsche 911 Carrera S',
      make: 'Porsche',
      model: '911',
      variant: 'Carrera S',
      year: 2023,
      price: 125000,
      financeMonthly: 1850,
      mileage: 2500,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'Coupe' as const,
      drivetrain: 'RWD' as const,
      colour: 'GT Silver Metallic',
      engineSize: '3.0L Twin-Turbo',
      doors: 2,
      seats: 4,
      registration: 'PO23 RSC',
      previousOwners: 1,
      description: 'Stunning Porsche 911 Carrera S in GT Silver Metallic. This exceptional sports car features the iconic flat-six engine, delivering breathtaking performance and precision handling. Immaculate condition with full Porsche service history.',
      status: 'available' as const,
      featured: true,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=1200&q=80',
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80',
      ],
      features: [
        'Sport Chrono Package',
        'Porsche Active Suspension Management',
        'Bose Surround Sound System',
        'Heated Sport Seats',
        'LED Matrix Headlights',
        'Porsche Communication Management',
        'Reversing Camera',
        'Adaptive Cruise Control',
      ],
    },
    {
      title: '2022 Ferrari Roma',
      make: 'Ferrari',
      model: 'Roma',
      variant: null,
      year: 2022,
      price: 189950,
      financeMonthly: 2799,
      mileage: 1200,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'Coupe' as const,
      drivetrain: 'RWD' as const,
      colour: 'Rosso Corsa',
      engineSize: '3.9L V8 Twin-Turbo',
      doors: 2,
      seats: 4,
      registration: 'FE22 RRI',
      previousOwners: 1,
      description: 'Exquisite Ferrari Roma in the iconic Rosso Corsa red. This modern GT combines timeless elegance with cutting-edge performance. The 620hp V8 delivers an intoxicating soundtrack and blistering acceleration. Barely driven and in pristine condition.',
      status: 'available' as const,
      featured: true,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=80',
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=80',
      ],
      features: [
        'Carbon Ceramic Brakes',
        'Ferrari Dynamic Enhancer',
        'Premium Leather Interior',
        'Apple CarPlay',
        'Parking Sensors Front & Rear',
        'Climate Control',
        'Alcantara Steering Wheel',
        'Racing Seats',
      ],
    },
    {
      title: '2023 Lamborghini Urus Performante',
      make: 'Lamborghini',
      model: 'Urus',
      variant: 'Performante',
      year: 2023,
      price: 215000,
      financeMonthly: 3150,
      mileage: 800,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'SUV' as const,
      drivetrain: 'AWD' as const,
      colour: 'Nero Noctis',
      engineSize: '4.0L V8 Twin-Turbo',
      doors: 5,
      seats: 5,
      registration: 'LA23 MBO',
      previousOwners: 1,
      description: 'The ultimate super SUV. This Lamborghini Urus Performante combines supercar performance with SUV practicality. Finished in sophisticated Nero Noctis with contrasting interior. Nearly new with comprehensive warranty remaining.',
      status: 'available' as const,
      featured: true,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1200&q=80',
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80',
      ],
      features: [
        'Carbon Ceramic Brakes',
        'Akrapovic Exhaust System',
        'Panoramic Sunroof',
        'Bang & Olufsen Sound System',
        '360 Degree Camera',
        'Adaptive Air Suspension',
        'Lamborghini Infotainment System',
        'Heated & Ventilated Seats',
      ],
    },
    {
      title: '2022 Bentley Bentayga V8',
      make: 'Bentley',
      model: 'Bentayga',
      variant: 'V8',
      year: 2022,
      price: 165000,
      financeMonthly: 2450,
      mileage: 3500,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'SUV' as const,
      drivetrain: 'AWD' as const,
      colour: 'Onyx Black',
      engineSize: '4.0L V8 Twin-Turbo',
      doors: 5,
      seats: 5,
      registration: 'BE22 NTY',
      previousOwners: 1,
      description: 'Magnificent Bentley Bentayga V8 in Onyx Black with Linen interior. The pinnacle of luxury SUVs, combining handcrafted British luxury with exceptional performance. Extensive specification including all the desirable options.',
      status: 'available' as const,
      featured: true,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&q=80',
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80',
      ],
      features: [
        'Naim for Bentley Audio',
        'Massage Seats',
        'Panoramic Glass Roof',
        'Night Vision',
        'Head-Up Display',
        'Bentley Rotating Display',
        'Mood Lighting',
        'Hands-Free Tailgate',
      ],
    },
    {
      title: '2023 Range Rover Sport P530',
      make: 'Land Rover',
      model: 'Range Rover Sport',
      variant: 'P530',
      year: 2023,
      price: 98500,
      financeMonthly: 1450,
      mileage: 1800,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'SUV' as const,
      drivetrain: 'AWD' as const,
      colour: 'Byron Blue',
      engineSize: '4.4L V8 Twin-Turbo',
      doors: 5,
      seats: 5,
      registration: 'RR23 SPT',
      previousOwners: 1,
      description: 'The new Range Rover Sport P530 in stunning Byron Blue. This flagship model combines luxury, performance, and cutting-edge technology. Barely run-in with full manufacturer warranty. An exceptional example of British automotive excellence.',
      status: 'available' as const,
      featured: true,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80',
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80',
      ],
      features: [
        'Air Suspension',
        'Meridian Signature Sound',
        'Panoramic Roof',
        'Matrix LED Headlights',
        'Configurable Ambient Lighting',
        'Heated & Cooled Front Seats',
        'Rear Executive Seating',
        'Terrain Response 2',
      ],
    },
    {
      title: '2022 Aston Martin DBX',
      make: 'Aston Martin',
      model: 'DBX',
      variant: null,
      year: 2022,
      price: 155000,
      financeMonthly: 2299,
      mileage: 2200,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'SUV' as const,
      drivetrain: 'AWD' as const,
      colour: 'Aston Martin Racing Green',
      engineSize: '4.0L V8 Twin-Turbo',
      doors: 5,
      seats: 5,
      registration: 'AM22 DBX',
      previousOwners: 1,
      description: 'Stunning Aston Martin DBX in the classic Racing Green. The first SUV from this legendary British marque combines sports car dynamics with SUV versatility. Impeccably maintained with full Aston Martin service history.',
      status: 'available' as const,
      featured: true,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=80',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80',
      ],
      features: [
        'Sports Plus Pack',
        'Premium Audio System',
        'Heated Windscreen',
        'Privacy Glass',
        '360 Degree Camera',
        'Adaptive Damping',
        'Keyless Entry',
        'Power Tailgate',
      ],
    },
    {
      title: '2021 Audi R8 V10 Performance',
      make: 'Audi',
      model: 'R8',
      variant: 'V10 Performance',
      year: 2021,
      price: 135000,
      financeMonthly: 1999,
      mileage: 4500,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'Coupe' as const,
      drivetrain: 'AWD' as const,
      colour: 'Suzuka Grey',
      engineSize: '5.2L V10',
      doors: 2,
      seats: 2,
      registration: 'AU21 DIR8',
      previousOwners: 1,
      description: 'Exceptional Audi R8 V10 Performance in Suzuka Grey. The naturally aspirated V10 engine produces an unforgettable soundtrack. This supercar offers everyday usability with exotic performance. Full Audi service history.',
      status: 'available' as const,
      featured: false,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=1200&q=80',
        'https://images.unsplash.com/photo-1610768764270-790fbec18178?w=1200&q=80',
      ],
      features: [
        'Carbon Ceramic Brakes',
        'Audi Virtual Cockpit Plus',
        'Bang & Olufsen Sound',
        'Laser Headlights',
        'Carbon Fiber Interior Pack',
        'Sports Exhaust',
        'Parking Sensors',
        'Reversing Camera',
      ],
    },
    {
      title: '2022 McLaren 720S Spider',
      make: 'McLaren',
      model: '720S',
      variant: 'Spider',
      year: 2022,
      price: 245000,
      financeMonthly: 3599,
      mileage: 1500,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'Convertible' as const,
      drivetrain: 'RWD' as const,
      colour: 'McLaren Orange',
      engineSize: '4.0L V8 Twin-Turbo',
      doors: 2,
      seats: 2,
      registration: 'MC22 LRN',
      previousOwners: 1,
      description: 'Breathtaking McLaren 720S Spider in signature McLaren Orange. This convertible supercar delivers mind-bending performance with the added thrill of open-top motoring. Carbon fiber monocoque construction and active aerodynamics.',
      status: 'reserved' as const,
      featured: false,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1200&q=80',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80',
      ],
      features: [
        'Carbon Ceramic Brakes',
        'McLaren Track Telemetry',
        'Bowers & Wilkins Audio',
        'Electrochromic Roof',
        'Alcantara Interior',
        'Parking Assist',
        'Vehicle Lift System',
        'Sports Exhaust',
      ],
    },
    {
      title: '2023 Mercedes-AMG G63',
      make: 'Mercedes-Benz',
      model: 'G-Class',
      variant: 'AMG G63',
      year: 2023,
      price: 175000,
      financeMonthly: 2599,
      mileage: 900,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'SUV' as const,
      drivetrain: 'AWD' as const,
      colour: 'Obsidian Black',
      engineSize: '4.0L V8 Twin-Turbo',
      doors: 5,
      seats: 5,
      registration: 'MB23 G63',
      previousOwners: 1,
      description: 'The iconic Mercedes-AMG G63 in Obsidian Black with full AMG specification. This legendary off-roader combines brutal performance with uncompromising luxury. Virtually brand new with full manufacturer warranty.',
      status: 'available' as const,
      featured: false,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&q=80',
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80',
      ],
      features: [
        'AMG Performance Exhaust',
        'Burmester 3D Surround Sound',
        'AMG Night Package',
        'Panoramic Sliding Roof',
        'Multibeam LED Headlights',
        'AMG Ride Control',
        'Heated & Ventilated Seats',
        'Widescreen Cockpit',
      ],
    },
    {
      title: '2021 Rolls-Royce Dawn Black Badge',
      make: 'Rolls-Royce',
      model: 'Dawn',
      variant: 'Black Badge',
      year: 2021,
      price: 285000,
      financeMonthly: 4199,
      mileage: 2800,
      transmission: 'Automatic' as const,
      fuelType: 'Petrol' as const,
      bodyType: 'Convertible' as const,
      drivetrain: 'RWD' as const,
      colour: 'Black Diamond',
      engineSize: '6.6L V12 Twin-Turbo',
      doors: 2,
      seats: 4,
      registration: 'RR21 DWN',
      previousOwners: 1,
      description: 'The ultimate expression of luxury motoring. This Rolls-Royce Dawn Black Badge combines the marque\'s legendary craftsmanship with a more dynamic character. Bespoke specification throughout with exquisite attention to detail.',
      status: 'available' as const,
      featured: false,
      published: true,
      images: [
        'https://images.unsplash.com/photo-1563720360172-67b8f3dce741?w=1200&q=80',
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80',
      ],
      features: [
        'Bespoke Audio System',
        'Starlight Headliner',
        'Heated & Cooled Seats',
        'Picnic Tables',
        'Spirit of Ecstasy Retractable',
        'Adaptive Headlights',
        'Night Vision',
        'Champagne Cooler',
      ],
    },
  ];

  for (const vehicle of luxuryVehicles) {
    const { images, features, ...vehicleData } = vehicle;
    const slug = generateSlug(`${vehicleData.year} ${vehicleData.make} ${vehicleData.model} ${vehicleData.variant || ''}`);

    const [insertedVehicle] = await db.insert(vehicles).values({
      ...vehicleData,
      price: vehicleData.price.toString(),
      financeMonthly: vehicleData.financeMonthly?.toString(),
      slug,
    }).returning();

    console.log(`Created vehicle: ${insertedVehicle.title}`);

    for (let i = 0; i < images.length; i++) {
      await db.insert(vehicleImages).values({
        vehicleId: insertedVehicle.id,
        imageUrl: images[i],
        altText: `${insertedVehicle.title} - Image ${i + 1}`,
        sortOrder: i,
      });
    }

    for (const feature of features) {
      await db.insert(vehicleFeatures).values({
        vehicleId: insertedVehicle.id,
        featureName: feature,
      });
    }
  }

  console.log('✅ Database seeded successfully!');
  process.exit(0);
}

seed().catch((error) => {
  console.error('❌ Seeding failed:', error);
  process.exit(1);
});
